version: 2
jobs:
   build:
      docker:
        - image: circleci/ruby:2.7.4-node
          environment:
            POSTGRES_USER: postgres 
            PGHOST: 127.0.0.1
            RAILS_ENV: test
        - image: circleci/postgres:9.6
          environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: searching_outlet_test
      working_directory: ~/searching_outlet
      steps:
        - checkout
        - restore_cache:
            keys:
              - v1-dependencies-{{ checksum "Gemfile.lock" }}
              - v1-dependencies-
        - run:
            name: install dependencies
            command: |
              gem install bundler -v 2.1.4
              bundle install --jobs=4 --retry=3 --path vendor/bundle
        - save_cache:
            key: v1-dependencies-{{ checksum "Gemfile.lock" }}
            paths:
              - ./vendor/bundle
        - run:
            name: start-up DB
            command: dockerize -wait tcp://127.0.0.1:5432 -timeout 120s
        - run: bundle exec rake db:create
        - run: bundle exec rake db:schema:load
        - run:
            name: yarn Install
            command: yarn install
        - run: bundle exec bin/webpack
        - run:
            name: rspec
            command: bundle exec rspec
        - run:
            name: rubocop
            command: bundle exec rubocop
        - deploy:
            name: Deploy Master to Heroku
            command:  git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:master
