version: 2
jobs:
  rspec:
    docker:
      - image: circleci/ruby:2.7.4-node-browsers
        environment:
          RAILS_ENV: test
          DB_HOST: 127.0.0.1
          DB_USERNAME: postgres
          DB_PASSWORD: password
      - image: circleci/postgres:9.6
        environment:
          POSTGRES_DATABASE: searching_outlet_test
          POSTGRES_USER: postgres
          POSTGRES_HOST_AUTH_METHOD: 'trust'
    working_directory: ~/searching_outlet
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run:
          name: update bundler
          command: |
            gem update --system
            gem install bundler:2.1.4
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}-{{ checksum "yarn.lock" }}
          paths:
            - ./vendor/bundle
      - run: bundle exec rails db:create RAILS_ENV=test
      - run: bundle exec rails db:schema:load RAILS_ENV=test
      - run:
          name: yarn Install
          command: yarn install
      - run: bundle exec bin/webpack
      - run:
          name: RSpec
          command: bundle exec rspec
  rubocop:
    docker:
      - image: circleci/ruby:2.7.4-node-browsers
        environment:
          RAILS_ENV: test
          DB_HOST: 127.0.0.1
          DB_USERNAME: postgres
          DB_PASSWORD: password
      - image: circleci/postgres:9.6
        environment:
          POSTGRES_DATABASE: searching_outlet_test
          POSTGRES_USER: postgres
          POSTGRES_ROOT_PASSWORD: password
    working_directory: ~/searching_outlet
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run:
          name: update bundler
          command: |
            gem update --system
            gem install bundler:2.1.4
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}-{{ checksum "yarn.lock" }}
          paths:
            - ./vendor/bundle
      - run: bundle exec rails db:create RAILS_ENV=test
      - run: bundle exec rails db:schema:load RAILS_ENV=test
      - run:
          name: RuboCop
          command: bundle exec rubocop

workflows:
  version: 2
  rspec_and_rubocop_workflow:
    jobs:
      - rspec
      - rubocop
